CREATE TABLE EMPLOYEE
        (
        id NUMBER(10) NOT NULL,
        name VARCHAR2(50) NOT NULL,
        PRIMARY KEY(id)
        );

  CREATE TABLE CATEGORY_TRANSLATIONS
   (	CATEGORY_ID NUMBER(15,0) NOT NULL ,
	CATEGORY_NAME VARCHAR2(50 ) NOT NULL ,
	CATEGORY_DESCRIPTION VARCHAR2(1000 ),
	LANGUAGE VARCHAR2(30 ) NOT NULL ,
	SOURCE_LANG VARCHAR2(30 ),
	CREATED_BY VARCHAR2(60 ) NOT NULL ,
	CREATION_DATE DATE NOT NULL ,
	LAST_UPDATED_BY VARCHAR2(60 ) NOT NULL ,
	LAST_UPDATE_DATE DATE NOT NULL ,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL ,
    CONSTRAINT CATEGORY_TRANSLATIONS_PK PRIMARY KEY (CATEGORY_ID, LANGUAGE)
   );

--    COMMENT ON COLUMN CATEGORY_TRANSLATIONS."CATEGORY_ID" IS 'Link to the category table';
--    COMMENT ON COLUMN CATEGORY_TRANSLATIONS."CATEGORY_NAME" IS 'Name of the category in the relevant language';
--    COMMENT ON COLUMN CATEGORY_TRANSLATIONS."CATEGORY_DESCRIPTION" IS 'Description of the category in the relevant language';
--    COMMENT ON COLUMN CATEGORY_TRANSLATIONS."LANGUAGE" IS 'Language assigned for this entry ';
--    COMMENT ON COLUMN CATEGORY_TRANSLATIONS."SOURCE_LANG" IS 'Actual language that the values are currently in. The value may not actually be translated, if LANGUAGE and SOURCE_LANG are the same then the row has been translated';
--    COMMENT ON COLUMN CATEGORY_TRANSLATIONS."CREATED_BY" IS 'History column';
--    COMMENT ON COLUMN CATEGORY_TRANSLATIONS."CREATION_DATE" IS 'History column';
--    COMMENT ON COLUMN CATEGORY_TRANSLATIONS."LAST_UPDATED_BY" IS 'History column';
--    COMMENT ON COLUMN CATEGORY_TRANSLATIONS."LAST_UPDATE_DATE" IS 'History column';
--    COMMENT ON COLUMN CATEGORY_TRANSLATIONS."OBJECT_VERSION_ID" IS 'History column';
--    COMMENT ON TABLE CATEGORY_TRANSLATIONS  IS 'Holds one translation for the  category text for each lanuage supported by the system.';


  CREATE TABLE PRODUCT_CATEGORIES_BASE
   ( CATEGORY_ID NUMBER(15,0) NOT NULL ,
	PARENT_CATEGORY_ID NUMBER(15,0),
	CATEGORY_LOCKED_FLAG VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ,
	REPRESENTATIVE_PRODUCT_ID NUMBER(15,0),
	CREATED_BY VARCHAR2(60 BYTE) NOT NULL ,
	CREATION_DATE DATE NOT NULL ,
	LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL ,
	LAST_UPDATE_DATE DATE NOT NULL ,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL ,
	CONSTRAINT PRODUCT_TAGS_PK PRIMARY KEY (CATEGORY_ID)
-- 	 CONSTRAINT "PRODUCT_CATEGORIES_LOCKED_CHK" CHECK (CATEGORY_LOCKED_FLAG in ('Y','N')) ,
-- 	 CONSTRAINT "PRODUCT_CATEGORIES_FK" FOREIGN KEY ("PARENT_CATEGORY_ID")
-- 	  REFERENCES "PRODUCT_CATEGORIES_BASE" ("CATEGORY_ID") ,
-- 	 CONSTRAINT "REPRESENTATIVE_PRODUCT_FK" FOREIGN KEY ("REPRESENTATIVE_PRODUCT_ID")
-- 	  REFERENCES "PRODUCTS_BASE" ("PRODUCT_ID") ENABLE
   )  ;

--    COMMENT ON COLUMN "PRODUCT_CATEGORIES_BASE"."CATEGORY_ID" IS 'Unique Id for the category';
--    COMMENT ON COLUMN "PRODUCT_CATEGORIES_BASE"."PARENT_CATEGORY_ID" IS 'The parent of this category in the hierachy';
--    COMMENT ON COLUMN "PRODUCT_CATEGORIES_BASE"."CATEGORY_LOCKED_FLAG" IS 'Boolean fag to define if new products may be assigned to this category or not ';
--    COMMENT ON COLUMN "PRODUCT_CATEGORIES_BASE"."REPRESENTATIVE_PRODUCT_ID" IS 'Links to a product which will be used to provide the sample image to illustrate the whole category.';
--    COMMENT ON COLUMN "PRODUCT_CATEGORIES_BASE"."CREATED_BY" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_CATEGORIES_BASE"."CREATION_DATE" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_CATEGORIES_BASE"."LAST_UPDATED_BY" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_CATEGORIES_BASE"."LAST_UPDATE_DATE" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_CATEGORIES_BASE"."OBJECT_VERSION_ID" IS 'History column';
--    COMMENT ON TABLE "PRODUCT_CATEGORIES_BASE"  IS 'The classification hierachy for a particular product. Categories can be nested and then a product is assigned to a particular category.  The actual names and descriptions for the categories are held in the separate CATEGORY_TRANSLATIONS table.';
--

  CREATE TABLE PRODUCT_TRANSLATIONS
   ( PRODUCT_ID NUMBER(15,0) NOT NULL ,
	LANGUAGE VARCHAR2(30) NOT NULL ,
	SOURCE_LANG VARCHAR2(30),
	DESCRIPTION VARCHAR2(4000) NOT NULL ,
	ADDITIONAL_INFO VARCHAR2(4000),
	CREATED_BY VARCHAR2(60) NOT NULL ,
	CREATION_DATE DATE NOT NULL ,
	LAST_UPDATED_BY VARCHAR2(60) NOT NULL ,
	LAST_UPDATE_DATE DATE NOT NULL ,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL ,
	 CONSTRAINT PRODUCT_TRANSLATIONS_PK PRIMARY KEY (PRODUCT_ID, LANGUAGE)
--   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "USERS"  ,
-- 	 CONSTRAINT "PRODUCT_TRANSLATIONS_FK" FOREIGN KEY ("PRODUCT_ID")
-- 	  REFERENCES "PRODUCTS_BASE" ("PRODUCT_ID") ENABLE
   ) ;

--    COMMENT ON COLUMN "PRODUCT_TRANSLATIONS"."PRODUCT_ID" IS 'Link to the product';
--    COMMENT ON COLUMN "PRODUCT_TRANSLATIONS"."LANGUAGE" IS 'Language code for this entry';
--    COMMENT ON COLUMN "PRODUCT_TRANSLATIONS"."SOURCE_LANG" IS 'Actual language that this entry is in. If the entry has not yet been translated this value may be different from the defined LANGUAGE of the entry';
--    COMMENT ON COLUMN "PRODUCT_TRANSLATIONS"."DESCRIPTION" IS 'Translated description of the product ';
--    COMMENT ON COLUMN "PRODUCT_TRANSLATIONS"."ADDITIONAL_INFO" IS 'More ionformation about the product such as technical specifications';
--    COMMENT ON COLUMN "PRODUCT_TRANSLATIONS"."CREATED_BY" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_TRANSLATIONS"."CREATION_DATE" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_TRANSLATIONS"."LAST_UPDATED_BY" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_TRANSLATIONS"."LAST_UPDATE_DATE" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_TRANSLATIONS"."OBJECT_VERSION_ID" IS 'History column';
--    COMMENT ON TABLE "PRODUCT_TRANSLATIONS"  IS 'Holds the translated names and descriptions of the product. One translation row will exist for each language supported by the system and each product';


CREATE TABLE PRODUCT_IMAGES
   (PRODUCT_IMAGE_ID NUMBER(15,0) NOT NULL, 
	PRODUCT_ID NUMBER(15,0) NOT NULL ,
	DEFAULT_VIEW_FLAG VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ,
	DETAIL_IMAGE_ID NUMBER(15,0), 
	IMAGE BLOB NOT NULL ,
	CREATED_BY VARCHAR2(60 ) NOT NULL ,
	CREATION_DATE DATE NOT NULL ,
	LAST_UPDATED_BY VARCHAR2(60 ) NOT NULL ,
	LAST_UPDATE_DATE DATE NOT NULL ,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL ,
	 CONSTRAINT "PRODUCT_IMAGES_PK" PRIMARY KEY ("PRODUCT_IMAGE_ID")
--   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "USERS"  
-- 	 CONSTRAINT "PRODUCT_IMAGES_DEFAULT_CHK" CHECK (DEFAULT_VIEW_FLAG in ('Y','N')) 
-- 	 CONSTRAINT "PRODUCT_IMAGES_FK" FOREIGN KEY ("DETAIL_IMAGE_ID")
-- 	  REFERENCES "PRODUCT_IMAGES" ("PRODUCT_IMAGE_ID") 
-- 	 CONSTRAINT "PRODUCT_IMAGES_PRODUCTS_FK" FOREIGN KEY ("PRODUCT_ID")
-- 	  REFERENCES "PRODUCTS_BASE" ("PRODUCT_ID") ENABLE
   ) ;



--    COMMENT ON COLUMN "PRODUCT_IMAGES"."PRODUCT_IMAGE_ID" IS 'Unique Id for images';
--    COMMENT ON COLUMN "PRODUCT_IMAGES"."PRODUCT_ID" IS 'Link to the associated product';
--    COMMENT ON COLUMN "PRODUCT_IMAGES"."DEFAULT_VIEW_FLAG" IS 'Only one image can be the default view. This will be the image show in the main catelog. Only one image for a particular product may have this flag set';
--    COMMENT ON COLUMN "PRODUCT_IMAGES"."DETAIL_IMAGE_ID" IS 'Allows for a drilldown from thumbnail view to a detailed version of the image';
--    COMMENT ON COLUMN "PRODUCT_IMAGES"."IMAGE" IS 'The image to show';
--    COMMENT ON COLUMN "PRODUCT_IMAGES"."CREATED_BY" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_IMAGES"."CREATION_DATE" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_IMAGES"."LAST_UPDATED_BY" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_IMAGES"."LAST_UPDATE_DATE" IS 'History column';
--    COMMENT ON COLUMN "PRODUCT_IMAGES"."OBJECT_VERSION_ID" IS 'History column';
--    COMMENT ON TABLE "PRODUCT_IMAGES"  IS 'Images of each product. A product many have several images available, only one of which will be marked as primary. Imgaes may also be thumbnails in which case the detailed version is pointed to by the DETAIL_IMAGE_ID';





  CREATE TABLE PRODUCTS_BASE
   ( PRODUCT_ID NUMBER(15,0) NOT NULL,
	SUPPLIER_ID NUMBER(15,0) NOT NULL ,
	PARENT_CATEGORY_ID NUMBER(15,0),
	CATEGORY_ID NUMBER(15,0),
	PRODUCT_NAME VARCHAR2(50 BYTE) NOT NULL ,
	PRODUCT_STATUS VARCHAR2(30 BYTE) NOT NULL ,
	COST_PRICE NUMBER(8,2),
	LIST_PRICE NUMBER(8,2) NOT NULL ,
	MIN_PRICE NUMBER(8,2) NOT NULL ,
	WARRANTY_PERIOD_MONTHS NUMBER(2,0),
	SHIPPING_CLASS_CODE VARCHAR2(30 BYTE) NOT NULL ,
	EXTERNAL_URL VARCHAR2(200 BYTE),
	ATTRIBUTE_CATEGORY VARCHAR2(30 BYTE),
	ATTRIBUTE1 VARCHAR2(150 BYTE),
	ATTRIBUTE2 VARCHAR2(150 BYTE),
	ATTRIBUTE3 VARCHAR2(150 BYTE),
	ATTRIBUTE4 VARCHAR2(150 BYTE),
	ATTRIBUTE5 VARCHAR2(150 BYTE),
	ATTRIBUTE6 VARCHAR2(150 BYTE),
	ATTRIBUTE7 VARCHAR2(150 BYTE),
	ATTRIBUTE8 VARCHAR2(150 BYTE),
	ATTRIBUTE9 VARCHAR2(150 BYTE),
	ATTRIBUTE10 VARCHAR2(150 BYTE),
	ATTRIBUTE11 VARCHAR2(150 BYTE),
	ATTRIBUTE12 VARCHAR2(150 BYTE),
	ATTRIBUTE13 VARCHAR2(150 BYTE),
	ATTRIBUTE14 VARCHAR2(150 BYTE),
	ATTRIBUTE15 VARCHAR2(150 BYTE),
	CREATED_BY VARCHAR2(60 BYTE) NOT NULL ,
	CREATION_DATE DATE NOT NULL ,
	LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL ,
	LAST_UPDATE_DATE DATE NOT NULL ,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL ,
	 CONSTRAINT "PRODUCTS_PK" PRIMARY KEY (PRODUCT_ID)
--   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "USERS"  
-- 	 CONSTRAINT "PRODUCTS_SUPPLIERS_FK" FOREIGN KEY ("SUPPLIER_ID")
-- 	  REFERENCES "SUPPLIERS" ("SUPPLIER_ID") 
-- 	 CONSTRAINT "PRODUCTS_PRODUCT_CATEGORIES_FK" FOREIGN KEY ("CATEGORY_ID")
-- 	  REFERENCES "PRODUCT_CATEGORIES_BASE" ("CATEGORY_ID") ENABLE
   )  ;

--    COMMENT ON COLUMN "PRODUCTS_BASE"."PRODUCT_ID" IS 'The unique identifier for this product';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."SUPPLIER_ID" IS 'The unique ID of the supplier of this product';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."CATEGORY_ID" IS 'The category to which this product belongs. This category us used to help in searching for and organizing the products in the Storefront.';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."PRODUCT_NAME" IS 'A descriptive name for this product.';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."COST_PRICE" IS 'The amount paid to the supplier for this product';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."LIST_PRICE" IS 'The suggested list price for the product';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."MIN_PRICE" IS 'The agreed minimum price (after discounts) for this product';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."WARRANTY_PERIOD_MONTHS" IS 'How long is the warantee for this product';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."SHIPPING_CLASS_CODE" IS 'Defines the weight class for this particular product. This is then used to calculate the shipping cost. Code is a lookup to the LOOKUP_CODES table with a domain of SHIPPING_CLASS_CODE';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."EXTERNAL_URL" IS 'Link back to the supplier website ';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE_CATEGORY" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE1" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE2" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE3" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE4" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE5" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE6" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE7" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE8" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE9" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE10" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE11" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE12" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE13" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."ATTRIBUTE14" IS 'Reserved for Applications use as Descriptive Flexfield';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."CREATED_BY" IS 'History column';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."CREATION_DATE" IS 'History column';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."LAST_UPDATED_BY" IS 'History column';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."LAST_UPDATE_DATE" IS 'History column';
--    COMMENT ON COLUMN "PRODUCTS_BASE"."OBJECT_VERSION_ID" IS 'History column';
--    COMMENT ON TABLE "PRODUCTS_BASE"  IS 'The products that are sold';



ALTER TABLE PRODUCT_CATEGORIES_BASE ADD
 	 CONSTRAINT PRODUCT_CATEGORIES_LOCKED_CHK CHECK (CATEGORY_LOCKED_FLAG in ('Y','N')) ;

ALTER TABLE PRODUCT_CATEGORIES_BASE ADD
 	 CONSTRAINT PRODUCT_CATEGORIES_FK FOREIGN KEY (PARENT_CATEGORY_ID)
 	  REFERENCES PRODUCT_CATEGORIES_BASE (CATEGORY_ID) ;

ALTER TABLE PRODUCT_CATEGORIES_BASE ADD
 	 CONSTRAINT REPRESENTATIVE_PRODUCT_FK FOREIGN KEY (REPRESENTATIVE_PRODUCT_ID)
 	  REFERENCES PRODUCTS_BASE (PRODUCT_ID) ;

ALTER TABLE  PRODUCT_TRANSLATIONS ADD
	 CONSTRAINT PRODUCT_TRANSLATIONS_FK FOREIGN KEY (PRODUCT_ID)
 	  REFERENCES PRODUCTS_BASE (PRODUCT_ID) ;

ALTER TABLE  PRODUCT_IMAGES  ADD
 	 CONSTRAINT PRODUCT_IMAGES_DEFAULT_CHK CHECK (DEFAULT_VIEW_FLAG in ('Y','N')) ;
ALTER TABLE  PRODUCT_IMAGES  ADD
 	 CONSTRAINT PRODUCT_IMAGES_FK FOREIGN KEY (DETAIL_IMAGE_ID)
 	  REFERENCES PRODUCT_IMAGES (PRODUCT_IMAGE_ID) ;

ALTER TABLE  PRODUCT_IMAGES  ADD
	 CONSTRAINT PRODUCT_IMAGES_PRODUCTS_FK FOREIGN KEY (PRODUCT_ID)
 	  REFERENCES PRODUCTS_BASE (PRODUCT_ID) ;

--       ALTER TABLE  PRODUCT_IMAGES  ADD
-- 	 CONSTRAINT "PRODUCTS_SUPPLIERS_FK" FOREIGN KEY ("SUPPLIER_ID")
-- 	  REFERENCES "SUPPLIERS" ("SUPPLIER_ID") ;

ALTER TABLE  PRODUCTS_BASE  ADD
 	 CONSTRAINT PRODUCTS_PRODUCT_CATEGORIES_FK FOREIGN KEY (CATEGORY_ID)
 	  REFERENCES PRODUCT_CATEGORIES_BASE (CATEGORY_ID) ;
