
  CREATE TABLE WAREHOUSES 
   (	WAREHOUSE_ID NUMBER(15,0) NOT NULL,
	ADDRESS_ID NUMBER(15,0) NOT NULL,
	WAREHOUSE_NAME VARCHAR2(35 BYTE) NOT NULL,
	CREATED_BY VARCHAR2(60 BYTE) NOT NULL,
	CREATION_DATE DATE NOT NULL,
	LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL,
	LAST_UPDATE_DATE DATE NOT NULL,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL,
	 CONSTRAINT WAREHOUSES_PK PRIMARY KEY (WAREHOUSE_ID)
-- 	 CONSTRAINT WAREHOUSES_ADDRESSES_FK FOREIGN KEY (ADDRESS_ID)
-- 	  REFERENCES ADDRESSES (ADDRESS_ID) ENABLE
   )  ;

--    COMMENT ON COLUMN WAREHOUSES.WAREHOUSE_ID IS 'Unique Id for a warehouse';
--    COMMENT ON COLUMN WAREHOUSES.ADDRESS_ID IS 'Address of the warehouse. A warehouse can only have one location so there is a direct link to addresses here rather than a link via the ADDRESS_USAGES table.';
--    COMMENT ON COLUMN WAREHOUSES.CREATED_BY IS 'History column';
--    COMMENT ON COLUMN WAREHOUSES.CREATION_DATE IS 'History column';
--    COMMENT ON COLUMN WAREHOUSES.LAST_UPDATED_BY IS 'History column';
--    COMMENT ON COLUMN WAREHOUSES.LAST_UPDATE_DATE IS 'History column';
--    COMMENT ON COLUMN WAREHOUSES.OBJECT_VERSION_ID IS 'History column';
--    COMMENT ON TABLE WAREHOUSES  IS 'Warehouses owned by the store''s company (not individual suppliers) ';
-- 
--   CREATE OR REPLACE TRIGGER ASSIGN_WAREHOUSE_ID BEFORE INSERT ON WAREHOUSES
-- FOR EACH ROW
-- BEGIN
--  IF :NEW.WAREHOUSE_ID IS NULL OR :NEW.WAREHOUSE_ID < 0 THEN
--    SELECT WAREHOUSE_SEQ.NEXTVAL
--      INTO :NEW.WAREHOUSE_ID
--      FROM DUAL;
--    END IF;
-- END;
-- /
-- ALTER TRIGGER ASSIGN_WAREHOUSE_ID ENABLE;




  CREATE TABLE WAREHOUSE_STOCK_LEVELS 
   (	PRODUCT_ID NUMBER(15,0) NOT NULL,
	WAREHOUSE_ID NUMBER(15,0) NOT NULL,
	QUANTITY_ON_HAND NUMBER(8,0) NOT NULL,
	CREATED_BY VARCHAR2(60 BYTE) NOT NULL,
	CREATION_DATE DATE NOT NULL,
	LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL,
	LAST_UPDATE_DATE DATE NOT NULL,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL,
	 CONSTRAINT WAREHOUSE_STOCK_LEVELS_PK PRIMARY KEY (PRODUCT_ID, WAREHOUSE_ID)
--   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE USERS
  ,
	 CONSTRAINT WAREHOUSE_STOCK_LEVELS_FK FOREIGN KEY (WAREHOUSE_ID)
	  REFERENCES WAREHOUSES (WAREHOUSE_ID)
-- 	 CONSTRAINT WAREHOUSE_STOCK_LEVELS_FK1 FOREIGN KEY (PRODUCT_ID)
-- 	  REFERENCES PRODUCTS_BASE (PRODUCT_ID) ENABLE
   )  ;

--    COMMENT ON COLUMN WAREHOUSE_STOCK_LEVELS.PRODUCT_ID IS 'Link to the product table';
--    COMMENT ON COLUMN WAREHOUSE_STOCK_LEVELS.WAREHOUSE_ID IS 'The warehouse in question ';
--    COMMENT ON COLUMN WAREHOUSE_STOCK_LEVELS.QUANTITY_ON_HAND IS 'The stock level of this product';
--    COMMENT ON COLUMN WAREHOUSE_STOCK_LEVELS.CREATED_BY IS 'History column';
--    COMMENT ON COLUMN WAREHOUSE_STOCK_LEVELS.CREATION_DATE IS 'History column';
--    COMMENT ON COLUMN WAREHOUSE_STOCK_LEVELS.LAST_UPDATED_BY IS 'History column';
--    COMMENT ON COLUMN WAREHOUSE_STOCK_LEVELS.LAST_UPDATE_DATE IS 'History column';
--    COMMENT ON COLUMN WAREHOUSE_STOCK_LEVELS.OBJECT_VERSION_ID IS 'History column';
--    COMMENT ON TABLE WAREHOUSE_STOCK_LEVELS  IS 'Holds information about the stock levels for a particular product in each warehouse.';

