
  CREATE TABLE SUPPLIERS 
   (	SUPPLIER_ID NUMBER(15,0) NOT NULL , 
	SUPPLIER_NAME VARCHAR2(120 BYTE) NOT NULL , 
	SUPPLIER_STATUS VARCHAR2(30 BYTE) NOT NULL , 
	PHONE_NUMBER VARCHAR2(20 BYTE), 
	EMAIL VARCHAR2(255 BYTE), 
	UI_SKIN VARCHAR2(60 BYTE), 
	CREATED_BY VARCHAR2(60 BYTE) NOT NULL , 
	CREATION_DATE DATE NOT NULL , 
	LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL , 
	LAST_UPDATE_DATE DATE NOT NULL , 
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL , 
	 CONSTRAINT SUPPLIERS_PK PRIMARY KEY (SUPPLIER_ID)
   )  ;

--    COMMENT ON COLUMN FOD.SUPPLIERS.SUPPLIER_ID IS 'Unique identifier for a supplier';
--    COMMENT ON COLUMN FOD.SUPPLIERS.SUPPLIER_NAME IS 'Supplier Name';
--    COMMENT ON COLUMN FOD.SUPPLIERS.CREATED_BY IS 'History column';
--    COMMENT ON COLUMN FOD.SUPPLIERS.CREATION_DATE IS 'History column';
--    COMMENT ON COLUMN FOD.SUPPLIERS.LAST_UPDATED_BY IS 'History column';
--    COMMENT ON COLUMN FOD.SUPPLIERS.LAST_UPDATE_DATE IS 'History column';
--    COMMENT ON COLUMN FOD.SUPPLIERS.OBJECT_VERSION_ID IS 'History column';
--    COMMENT ON TABLE FOD.SUPPLIERS  IS 'This table holds a list of product suppliers';
-- 
--   CREATE OR REPLACE TRIGGER FOD.ASSIGN_SUPPLIER_ID BEFORE INSERT ON SUPPLIERS
-- FOR EACH ROW
-- BEGIN
--  IF :NEW.SUPPLIER_ID IS NULL OR :NEW.SUPPLIER_ID < 0 THEN
--    SELECT SUPPLIER_SEQ.NEXTVAL
--      INTO :NEW.SUPPLIER_ID
--      FROM DUAL;
--    END IF;
-- END;
-- /
-- ALTER TRIGGER FOD.ASSIGN_SUPPLIER_ID ;

