
  CREATE TABLE COUNTRY_CODES
   (	ISO_COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL,
	COUNTRY_NAME VARCHAR2(100 BYTE),
	LANGUAGE VARCHAR2(30 BYTE) NOT NULL,
	SOURCE_LANG VARCHAR2(30 BYTE),
	CREATED_BY VARCHAR2(60 BYTE) NOT NULL,
	CREATION_DATE DATE NOT NULL,
	LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL,
	LAST_UPDATE_DATE DATE NOT NULL,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL,
	 CONSTRAINT COUNTRY_CODES_PK PRIMARY KEY (ISO_COUNTRY_CODE, LANGUAGE)
--   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE USERS  ENABLE
   )
--    SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE USERS
   ;

--    COMMENT ON COLUMN COUNTRY_CODES.ISO_COUNTRY_CODE IS 'The actual country code';
--    COMMENT ON COLUMN COUNTRY_CODES.COUNTRY_NAME IS 'Translated country name';
--    COMMENT ON COLUMN COUNTRY_CODES.LANGUAGE IS 'Language that this row represents';
--    COMMENT ON COLUMN COUNTRY_CODES.SOURCE_LANG IS 'Actual language that this row is currently in. May not necessarily match the LANGUGE value if the entry has yet to be translated';
--    COMMENT ON COLUMN COUNTRY_CODES.CREATED_BY IS 'History column';
--    COMMENT ON COLUMN COUNTRY_CODES.CREATION_DATE IS 'History column';
--    COMMENT ON COLUMN COUNTRY_CODES.LAST_UPDATED_BY IS 'History column';
--    COMMENT ON COLUMN COUNTRY_CODES.LAST_UPDATE_DATE IS 'History column';
--    COMMENT ON COLUMN COUNTRY_CODES.OBJECT_VERSION_ID IS 'History column';
--    COMMENT ON TABLE COUNTRY_CODES  IS 'List of ISO Country codes and the name of the relevant country. This contains the translations for each country name as well. So each country code will be repeated for each supported language';
--



  CREATE TABLE LOOKUP_CODES
   (	LOOKUP_TYPE VARCHAR2(30 BYTE) NOT NULL,
	LOOKUP_CODE VARCHAR2(30 BYTE) NOT NULL,
	MEANING VARCHAR2(80 BYTE) NOT NULL,
	DESCRIPTION VARCHAR2(240 BYTE),
	LANGUAGE VARCHAR2(30 BYTE) NOT NULL,
	SOURCE_LANG VARCHAR2(30 BYTE) NOT NULL,
	CREATED_BY VARCHAR2(60 BYTE) NOT NULL,
	CREATION_DATE DATE NOT NULL,
	LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL,
	LAST_UPDATE_DATE DATE NOT NULL,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL,
	 CONSTRAINT LOOKUP_CODES_PK PRIMARY KEY (LOOKUP_TYPE, LOOKUP_CODE, LANGUAGE)
--   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE USERS  ENABLE
   )
--    SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE USERS
   ;

--    COMMENT ON COLUMN LOOKUP_CODES.LOOKUP_TYPE IS 'The domain to use ';
--    COMMENT ON COLUMN LOOKUP_CODES.LOOKUP_CODE IS 'The code to match';
--    COMMENT ON COLUMN LOOKUP_CODES.MEANING IS 'What the code means';
--    COMMENT ON COLUMN LOOKUP_CODES.DESCRIPTION IS 'Further qualification of the meaning';
--    COMMENT ON COLUMN LOOKUP_CODES.LANGUAGE IS 'The language that this row represents';
--    COMMENT ON COLUMN LOOKUP_CODES.SOURCE_LANG IS 'The actual language that the strings in this row are in - this may not match the LANGUAGE column if the row has not yet been translated';
--    COMMENT ON COLUMN LOOKUP_CODES.CREATED_BY IS 'History column';
--    COMMENT ON COLUMN LOOKUP_CODES.CREATION_DATE IS 'History column';
--    COMMENT ON COLUMN LOOKUP_CODES.LAST_UPDATED_BY IS 'History column';
--    COMMENT ON COLUMN LOOKUP_CODES.LAST_UPDATE_DATE IS 'History column';
--    COMMENT ON COLUMN LOOKUP_CODES.OBJECT_VERSION_ID IS 'History column';
--    COMMENT ON TABLE LOOKUP_CODES  IS 'Codes used throughout the system following the standard pattern of code Domains specifying to what a code is used for. ';



  CREATE TABLE HELP_TRANSLATIONS
   (	HELP_TRANSLATIONS_ID NUMBER(15,0) NOT NULL,
	HELP_ID NUMBER(15,0) NOT NULL,
	HELP_USAGE VARCHAR2(200 BYTE) NOT NULL,
	HELP_TEXT VARCHAR2(2000 BYTE) NOT NULL,
	LANGUAGE VARCHAR2(30 BYTE) NOT NULL,
	SOURCE_LANGUAGE VARCHAR2(15 BYTE) NOT NULL,
	CREATED_BY VARCHAR2(60 BYTE) NOT NULL,
	CREATION_DATE DATE NOT NULL,
	LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL,
	LAST_UPDATE_DATE DATE NOT NULL,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL,
	 CONSTRAINT HELP_TRANSLATIONS_PK PRIMARY KEY (HELP_TRANSLATIONS_ID)
--   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE USERS  ENABLE
   )
--     SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE USERS
   ;

--    COMMENT ON COLUMN HELP_TRANSLATIONS.HELP_ID IS 'Reserved for future use - the link to a base help table';
--    COMMENT ON COLUMN HELP_TRANSLATIONS.HELP_USAGE IS 'The usage of this text as it relates to the application';
--    COMMENT ON COLUMN HELP_TRANSLATIONS.HELP_TEXT IS 'The translated help text';
--    COMMENT ON COLUMN HELP_TRANSLATIONS.LANGUAGE IS 'The language that this translation row represents ';
--    COMMENT ON COLUMN HELP_TRANSLATIONS.SOURCE_LANGUAGE IS 'The actual language that this row is in - it may not match the LANGUAGE column if the row has not actually been translated yet';
--    COMMENT ON COLUMN HELP_TRANSLATIONS.CREATED_BY IS 'History column';
--    COMMENT ON COLUMN HELP_TRANSLATIONS.CREATION_DATE IS 'History column';
--    COMMENT ON COLUMN HELP_TRANSLATIONS.LAST_UPDATED_BY IS 'History column';
--    COMMENT ON COLUMN HELP_TRANSLATIONS.LAST_UPDATE_DATE IS 'History column';
--    COMMENT ON COLUMN HELP_TRANSLATIONS.OBJECT_VERSION_ID IS 'History column';
--    COMMENT ON TABLE HELP_TRANSLATIONS  IS 'Holds translations of the application help text';
--
--   CREATE OR REPLACE TRIGGER ASSIGN_HELP_TRANS_ID BEFORE INSERT ON HELP_TRANSLATIONS
-- FOR EACH ROW
-- BEGIN
--  IF :NEW.HELP_TRANSLATIONS_ID IS NULL OR :NEW.HELP_TRANSLATIONS_ID < 0 THEN
--    SELECT HELP_TRANSLATIONS_SEQ.NEXTVAL
--      INTO :NEW.HELP_TRANSLATIONS_ID
--      FROM DUAL;
--    END IF;
-- END;
-- /
-- ALTER TRIGGER ASSIGN_HELP_TRANS_ID ENABLE;




  CREATE TABLE AVAILABLE_LANGUAGES
   (	LANGUAGE VARCHAR2(30 BYTE) NOT NULL,
	DEFAULT_FLAG VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
	CREATED_BY VARCHAR2(60 BYTE) NOT NULL,
	CREATION_DATE DATE NOT NULL,
	LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL,
	LAST_UPDATE_DATE DATE NOT NULL,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL,
	 CONSTRAINT AVAILABLE_LANGUAGES_PK PRIMARY KEY (LANGUAGE),
--   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE USERS ,
	 CONSTRAINT AVAILABLE_LANGUAGES_DEFLT_CHK CHECK (DEFAULT_FLAG in ('Y','N'))
   )
--     SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE USERS
   ;

--    COMMENT ON COLUMN AVAILABLE_LANGUAGES.LANGUAGE IS 'The supported language';
--    COMMENT ON COLUMN AVAILABLE_LANGUAGES.DEFAULT_FLAG IS 'Is this the system base language? Boolean Flag Y or N';
--    COMMENT ON COLUMN AVAILABLE_LANGUAGES.CREATED_BY IS 'History column';
--    COMMENT ON COLUMN AVAILABLE_LANGUAGES.CREATION_DATE IS 'History column';
--    COMMENT ON COLUMN AVAILABLE_LANGUAGES.LAST_UPDATED_BY IS 'History column';
--    COMMENT ON COLUMN AVAILABLE_LANGUAGES.LAST_UPDATE_DATE IS 'History column';
--    COMMENT ON COLUMN AVAILABLE_LANGUAGES.OBJECT_VERSION_ID IS 'History column';
--    COMMENT ON TABLE AVAILABLE_LANGUAGES  IS 'AVAILABLE_LANGUAGES lists all of the translations that are available in the system. Any translation table will be fully populated with one instance per available language. The entry itself may not yet be translated, in which case, the SOURCE_LANGUAGE column in the translation table will hold the language that the entry is currently in. When a value has been translated SOURCE_LANGUAGE and LANGUAGE will be the same. Only one row in this table will have the DEFAULT_FLAG set to Y ';
--


  CREATE TABLE DEMO_OPTIONS 
   (	KEY VARCHAR2(40 BYTE) NOT NULL, 
	VALUE VARCHAR2(120 BYTE), 
	JAVA_DATA_TYPE VARCHAR2(120 BYTE) DEFAULT 'java.lang.String' NOT NULL, 
	DESCRIPTION VARCHAR2(4000 BYTE) NOT NULL, 
	 CONSTRAINT DEMO_OPTIONS_PK PRIMARY KEY (KEY)
--   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE USERS  ENABLE
   )
--    SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE USERS
  ;

--    COMMENT ON COLUMN DEMO_OPTIONS.KEY IS 'Key Value to identify the preference. This will use a basic dot notation in the naming. e.g.  override.customer.email';
--    COMMENT ON COLUMN DEMO_OPTIONS.VALUE IS 'The value for the property. If this is set to NULL then the behavior of the preference will depend on context. For example setting an override.* property to null will indicate that the override is not in use and the real value will be used.  The type of a preference will genarlly be String. However, should an alternative type be required the value here should be valid for that type and the JAVA_DATA_TYPE set accordingly';
--    COMMENT ON COLUMN DEMO_OPTIONS.JAVA_DATA_TYPE IS 'Data Type of the setting value';
--    COMMENT ON COLUMN DEMO_OPTIONS.DESCRIPTION IS 'Describes the use of the setting. All settings must be fully explained and define what the valid values are.';
--    COMMENT ON TABLE DEMO_OPTIONS  IS 'Demo Settings defines the various options within the demo which are switched on. It also caches general configuration information such as email addresses and phone numbers to use as overrides in a demo scenario (where emails etc. may be fake)';
--
--


