
  CREATE TABLE SHIPPING_OPTIONS_BASE
   (	SHIPPING_OPTION_ID NUMBER(15,0) NOT NULL ,
	COUNTRY_CODE VARCHAR2(2 BYTE),
	COST_PER_CLASS1_ITEM NUMBER(8,2) NOT NULL ,
	COST_PER_CLASS2_ITEM NUMBER(8,2) NOT NULL ,
	COST_PER_CLASS3_ITEM NUMBER(8,2) NOT NULL ,
	FREE_SHIPPING_ALLOWED_FLAG VARCHAR2(1 BYTE) DEFAULT 'N',
	CREATED_BY VARCHAR2(60 BYTE) NOT NULL ,
	CREATION_DATE DATE NOT NULL ,
	LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL ,
	LAST_UPDATE_DATE DATE NOT NULL ,
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL ,
	 CONSTRAINT SHIPPING_OPTIONS_PK PRIMARY KEY (SHIPPING_OPTION_ID),
	 CONSTRAINT SHIPPING_OPTIONS_FREE_CHK CHECK (FREE_SHIPPING_ALLOWED_FLAG  in ('Y','N')) 
   ) ;

--    COMMENT ON COLUMN SHIPPING_OPTIONS_BASE.SHIPPING_OPTION_ID IS 'Unique Id for the shipping method';
--    COMMENT ON COLUMN SHIPPING_OPTIONS_BASE.COUNTRY_CODE IS 'Link to the COUNTRY_CODES table. The various types of shipping have different costs for each target country. For the sake of brevity, this table is populated with costs for the a small set of countries. A null country code indicates the rest of the world as a catch all.';
--    COMMENT ON COLUMN SHIPPING_OPTIONS_BASE.COST_PER_CLASS1_ITEM IS 'Unit cost for shipping CLASS1 items';
--    COMMENT ON COLUMN SHIPPING_OPTIONS_BASE.COST_PER_CLASS2_ITEM IS 'Unit cost for shipping CLASS2 items';
--    COMMENT ON COLUMN SHIPPING_OPTIONS_BASE.COST_PER_CLASS3_ITEM IS 'Unit cost for shipping CLASS3 items';
--    COMMENT ON COLUMN SHIPPING_OPTIONS_BASE.FREE_SHIPPING_ALLOWED_FLAG IS 'Boolean flag to indicate if this is a deductable shipping cost. In most cases this will only be set to Y for non-express shipping options';
--    COMMENT ON COLUMN SHIPPING_OPTIONS_BASE.CREATED_BY IS 'History column';
--    COMMENT ON COLUMN SHIPPING_OPTIONS_BASE.CREATION_DATE IS 'History column';
--    COMMENT ON COLUMN SHIPPING_OPTIONS_BASE.LAST_UPDATED_BY IS 'History column';
--    COMMENT ON COLUMN SHIPPING_OPTIONS_BASE.LAST_UPDATE_DATE IS 'History column';
--    COMMENT ON COLUMN SHIPPING_OPTIONS_BASE.OBJECT_VERSION_ID IS 'History column';
--    COMMENT ON TABLE SHIPPING_OPTIONS_BASE  IS 'This table drives the available shipping options for the order. This list is used by the UI and configured based on the shipping address''s country code. ';
-- 
--   CREATE OR REPLACE TRIGGER ASSIGN_SHIPPING_OPTION_ID BEFORE INSERT ON SHIPPING_OPTIONS_BASE
-- FOR EACH ROW
-- BEGIN
--  IF :NEW.SHIPPING_OPTION_ID IS NULL OR :NEW.SHIPPING_OPTION_ID < 0 THEN
--    SELECT SHIPPING_OPTION_SEQ.NEXTVAL
--      INTO :NEW.SHIPPING_OPTION_ID
--      FROM DUAL;
--    END IF;
-- END;
-- /
-- ALTER TRIGGER ASSIGN_SHIPPING_OPTION_ID ;





  CREATE TABLE SHIPPING_OPTION_TRANSLATIONS 
   (	SHIPPING_TRANSLATIONS_ID NUMBER(15,0) NOT NULL , 
	SHIPPING_OPTION_ID NUMBER(15,0) NOT NULL , 
	SHIPPING_METHOD VARCHAR2(100 BYTE) NOT NULL , 
	LANGUAGE VARCHAR2(30 BYTE) NOT NULL , 
	SOURCE_LANG VARCHAR2(4000 BYTE) NOT NULL , 
	CREATED_BY VARCHAR2(60 BYTE) NOT NULL , 
	CREATION_DATE DATE NOT NULL , 
	LAST_UPDATED_BY VARCHAR2(60 BYTE) NOT NULL , 
	LAST_UPDATE_DATE DATE NOT NULL , 
	OBJECT_VERSION_ID NUMBER(15,0) NOT NULL , 
	 CONSTRAINT SHIPPING_OPTION_TRANSLATI_PK PRIMARY KEY (SHIPPING_TRANSLATIONS_ID), 
	 CONSTRAINT SHIPPING_OPTION_TRANSLATION_FK FOREIGN KEY (SHIPPING_OPTION_ID)
	  REFERENCES SHIPPING_OPTIONS_BASE (SHIPPING_OPTION_ID) 
   )  ;

--    COMMENT ON COLUMN SHIPPING_OPTION_TRANSLATIONS.SHIPPING_OPTION_ID IS 'Link to the shipping option ';
--    COMMENT ON COLUMN SHIPPING_OPTION_TRANSLATIONS.SHIPPING_METHOD IS 'Translated description';
--    COMMENT ON COLUMN SHIPPING_OPTION_TRANSLATIONS.LANGUAGE IS 'The language that this row represents';
--    COMMENT ON COLUMN SHIPPING_OPTION_TRANSLATIONS.SOURCE_LANG IS 'The actual language that this entry is currently in. This value may not match the LANGUAGE column if the entry has yet to be translated.';
--    COMMENT ON COLUMN SHIPPING_OPTION_TRANSLATIONS.CREATED_BY IS 'History column';
--    COMMENT ON COLUMN SHIPPING_OPTION_TRANSLATIONS.CREATION_DATE IS 'History column';
--    COMMENT ON COLUMN SHIPPING_OPTION_TRANSLATIONS.LAST_UPDATED_BY IS 'History column';
--    COMMENT ON COLUMN SHIPPING_OPTION_TRANSLATIONS.LAST_UPDATE_DATE IS 'History column';
--    COMMENT ON COLUMN SHIPPING_OPTION_TRANSLATIONS.OBJECT_VERSION_ID IS 'History column';
--    COMMENT ON TABLE SHIPPING_OPTION_TRANSLATIONS  IS 'Holds the translated shipping option description. One translation will exist for each supported language and shipping option combination';
-- 
--   CREATE OR REPLACE TRIGGER ASSIGN_SHIPPING_TRANS_ID BEFORE INSERT ON SHIPPING_OPTION_TRANSLATIONS
-- FOR EACH ROW
-- BEGIN
--  IF :NEW.SHIPPING_TRANSLATIONS_ID IS NULL OR :NEW.SHIPPING_TRANSLATIONS_ID < 0 THEN
--    SELECT SHIPPING_TRANSLATIONS_SEQ.NEXTVAL
--      INTO :NEW.SHIPPING_TRANSLATIONS_ID
--      FROM DUAL;
--    END IF;
-- END;
-- /
-- ALTER TRIGGER ASSIGN_SHIPPING_TRANS_ID ;


